[env:esp32]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
board_build.partitions = ESP32_4MB_PARTITION_OTA.csv
lib_compat_mode = strict
lib_ldf_mode = chain

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed    = 921600  ; 921600, 512000, 460800, 256000, 115200

build_flags=
  -I include
  -D SERIAL_DEBUG=1
  -D CORE_DEBUG_LEVEL=3               ; 0 None, 1 Error, 2 Warn, 3 Info, 4 Debug, 5 Verbose

lib_deps =
  ESP32Async/AsyncTCP@3.4.9
  ESP32Async/ESPAsyncWebServer@3.9.3
  vshymanskyy/Preferences
  https://github.com/electro-adi/AdiWiFiManager.git
  https://github.com/Bodmer/TFT_eSPI.git
  adafruit/Adafruit NeoPixel
  sparkfun/SX1509 IO Expander
  https://github.com/Thinary/AHT10.git
  dfrobot/DFRobot_VL53L0X@^1.0.0
  dawidchyrzynski/home-assistant-integration
  https://github.com/electro-adi/Keypad_SX1509.git