[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
lib_compat_mode = strict
lib_ldf_mode = chain

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed    = 921600  ; 921600, 512000, 460800, 256000, 115200

build_flags=
  -D SERIAL_DEBUG=1

lib_deps =
  https://github.com/Bodmer/TFT_eSPI.git
  ESP32Async/AsyncTCP@3.4.9
  ESP32Async/ESPAsyncWebServer@3.9.3
  adafruit/Adafruit NeoPixel
  end2endzone/AnyRtttl
  vshymanskyy/Preferences
  sparkfun/SX1509 IO Expander
  adafruit/Adafruit AHTX0
  adafruit/Adafruit_VL53L0X